name: sucre
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.10.8
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - pip:
    - opencv-python==4.6.0.66
    - pyyaml==6.0
    - scipy==1.9.3
    - tensorboard==2.11.0
    - tqdm==4.64.1
